# Generated by Django 4.1.2 on 2022-10-29 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0012_alter_news_image_alter_news_text'),
        ('app_news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_parser.news'),
        ),
    ]
