# Generated by Django 4.1.2 on 2022-10-24 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='publication_date',
        ),
    ]
