# Generated by Django 4.1.2 on 2022-10-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0002_remove_news_publication_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='link',
            new_name='url',
        ),
    ]
