# Generated by Django 4.1.2 on 2022-11-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0002_exchangerates_alter_news_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'ordering': ('-creation_date_rates',)},
        ),
        migrations.AlterField(
            model_name='exchangerates',
            name='creation_date_rates',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='creation_date_news',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
