# Generated by Django 4.1.2 on 2022-10-26 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0003_rename_link_news_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='image',
        ),
    ]
