# Generated by Django 4.1.2 on 2022-10-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0004_remove_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='url',
            new_name='image',
        ),
        migrations.AddField(
            model_name='news',
            name='text',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=400),
        ),
    ]
