# Generated by Django 4.1.2 on 2022-11-06 11:57

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_parser', '0004_alter_exchangerates_options_copyrightarticles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CopyrightArticles',
            new_name='AuthorsArticles',
        ),
    ]
