# Generated by Django 4.1.2 on 2022-11-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0005_rename_copyrightarticles_authorsarticles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='comment_text',
            field=models.TextField(verbose_name='Текст комментария:'),
        ),
    ]
