# Generated by Django 4.1.2 on 2022-11-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0007_alter_comments_options_alter_exchangerates_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'ordering': ('creation_date_rates',)},
        ),
    ]
