# Generated by Django 4.1.2 on 2022-10-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0009_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text',
            field=models.CharField(max_length=20),
        ),
    ]
