# Generated by Django 4.1.2 on 2022-11-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0009_alter_exchangerates_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exchangerates',
            options={'ordering': ('creation_date_rates',)},
        ),
    ]
