# Generated by Django 4.1.2 on 2022-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0010_alter_exchangerates_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorsarticles',
            name='moderation_done',
            field=models.BooleanField(default=False),
        ),
    ]
