# Generated by Django 4.1.2 on 2022-11-08 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0011_authorsarticles_moderation_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsarticles',
            options={'ordering': ('creation_date',)},
        ),
    ]
