# Generated by Django 4.1.2 on 2022-11-09 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_parser', '0012_alter_authorsarticles_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsarticles',
            options={'ordering': ('creation_date',), 'verbose_name': 'Авторская статья', 'verbose_name_plural': 'Авторские статьи'},
        ),
        migrations.AlterField(
            model_name='authorsarticles',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
        ),
        migrations.AlterField(
            model_name='authorsarticles',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='authorsarticles',
            name='moderation_done',
            field=models.BooleanField(default=None, verbose_name='Модерация выполнена'),
        ),
        migrations.AlterField(
            model_name='authorsarticles',
            name='text_article',
            field=models.TextField(verbose_name='Текст статьи'),
        ),
        migrations.AlterField(
            model_name='authorsarticles',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Статья'),
        ),
    ]
