# Generated by Django 4.1.2 on 2022-10-29 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0013_comments'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-created',)},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='comment_text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='creation_date',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='news',
        ),
        migrations.AddField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_parser.news'),
            preserve_default=False,
        ),
    ]
