# Generated by Django 4.1.2 on 2022-10-30 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_parser', '0014_alter_comments_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-creation_date',)},
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='content',
            new_name='comment_text',
        ),
        migrations.RenameField(
            model_name='comments',
            old_name='created',
            new_name='creation_date',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='post',
        ),
        migrations.AddField(
            model_name='comments',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_parser.news'),
            preserve_default=False,
        ),
    ]
